### ISSUE TITLE
Add a way to apply transformations to the tweet text

### ISSUE THREAD

**Issue by claytron** [claytron/augury#8]
Maybe a series of regex you could apply to all tweets or by username?

For instance, [this tweet from seinfeldtoday](https://twitter.com/SeinfeldToday/status/618848531244126209):

```
When George falls for a Twitter bot, Kramer claims he once Catfished himself. J:How’s that even possible? K:Oh I’m good Jerry. I’m real good
```
Could be transformed to:

```
When George falls for a Twitter bot, Kramer claims he once Catfished himself.

Jerry: How’s that even possible?
Kramer: Oh I’m good Jerry. I’m real good
```

**Comment by claytron** [comment]
Can now format Modern Seinfeld as follows and get more legible results:

```yaml
transforms:
  seinfeldtoday:
    -
      - !ruby/regexp /J:\s*|JERRY:\s*/
      - "\n\nJerry: "
    -
      - !ruby/regexp /G:\s*|GEORGE:\s*/
      - "\n\nGeorge: "
    -
      - !ruby/regexp /E:\s*|ELAINE:\s*/
      - "\n\nElaine: "
    -
      - !ruby/regexp /K:\s*|KRAMER:\s*/
      - "\n\nKramer: "
    -
      - !ruby/regexp /GF:\s*/
      - "\n\nGirlfriend: "
```

Part of what inspired this change was Shit User Stories 😎 

```yaml
remove_links: true

transforms:
  shituserstories:
    -
      - !ruby/regexp /(i want to)/i
      - "\n\\1"
    -
      - !ruby/regexp /(so that)/i
      - "\n\\1"
```

Which becomes much nicer with the above config!
